### ISSUE TITLE
没有完整的例子

### ISSUE THREAD

**Issue by wildboy850** [eggjs/egg-jsonp#2]
egg-jsonp在controller里面的处理怎么写，callback的回调函数怎么写

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/controller.html#jsonp

另外后面 issue 麻烦去 https://github.com/eggjs/egg/issues 提，这边我等会关掉入口。

**Comment by atian25** [comment]
jsonp 插件也是 egg 内置的，无需自己引入。

**Comment by wildboy850** [comment]
thank you
